CREATE DATABASE IF NOT EXISTS NZ_COURT_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS NZ_COURT_INTELLIGENCE.RAW;
CREATE SCHEMA IF NOT EXISTS NZ_COURT_INTELLIGENCE.ANALYTICS;

CREATE TABLE IF NOT EXISTS NZ_COURT_INTELLIGENCE.RAW.DOCUMENTS (
    DOCUMENT_ID STRING NOT NULL,
    SHA256 STRING NOT NULL,
    FILENAME STRING NOT NULL,
    SOURCE_URL STRING,
    PAGE_COUNT NUMBER,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS NZ_COURT_INTELLIGENCE.RAW.CASE_EXTRACTIONS (
    EXTRACTION_ID STRING NOT NULL,
    DOCUMENT_ID STRING NOT NULL,
    MODEL_ID STRING,
    EXTRACTION VARIANT NOT NULL,
    VALIDATION VARIANT NOT NULL,
    EXTRACTION_STATUS STRING NOT NULL,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
